namespace PrimeGames.SDK.Common {

    public enum PlatformType {
        Localhost,
        NintendoSwitch,
        Editor,
        Unknown,
        AmazonAppStore,
        AppleAppStore,
        Aptoide,
        HuaweiAppGallery,
        GooglePlay,
        MiAppMall,
        OneStore,
        RuStore,
        SamsungGalaxyStore,
        XiaomiGames,
        Steam,
        VKPlay,
        UniversalWeb,
        CrazyGames,
        GameDistribution,
        Poki,
        Y8,
        YandexGames,
        OK,
        VK,
        PlayDeck,
        Telegram,
        CoolMath,
        Lagged,
        Zygomatic,
        MSN,
        Xiaomi,
        GamePix,
        PrimeHub,
        PlaygamaBridge,
        LumixGames,
        WelwiseGames,
        Playgama,
        Facebook,
        QATool,
        Discord,
        GamePush,
    }

}
